spring:
  swagger:
    enabled: true
    title: 示例代码
    description: 示例代码模块
    version: v1.0
    contact:
      name: zhanghaifeng
#    base-package: swagger扫描的基础包，默认：全扫描(分组情况下此处可不配置)
    #全局参数,比如Token之类的验证信息可以全局话配置
    global-operation-parameters:
    -   description: 'Token信息,必填项'
        modelRef: 'string'
        name: 'Authorization'
        parameter-type: 'header'
        required: true
#    groups:
#      basic-group:
#        base-package: com.battcn.controller.basic
#      system-group:
#        base-package: com.battcn.controller.system