spring:
  application:
    name: vcloud-core
    
#server.tomcat.uri-encoding=UTF-8
#spring.http.encoding.force=true
#spring.http.encoding.enabled=true
#spring.http.encoding.charset=UTF-8
#spring.messages.encoding=UTF-8